// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendasWebMvc.Data;

#nullable disable

namespace VendasWebMvc.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230103210524_1_primeira_migration")]
    partial class _1_primeira_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VendasWebMvc.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("VendasWebMvc.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("SalesRecord");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 11000.0,
                            Date = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 7000.0,
                            Date = new DateTime(2018, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4000.0,
                            Date = new DateTime(2018, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 8000.0,
                            Date = new DateTime(2018, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3000.0,
                            Date = new DateTime(2018, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 2000.0,
                            Date = new DateTime(2018, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 13000.0,
                            Date = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 4000.0,
                            Date = new DateTime(2018, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 11000.0,
                            Date = new DateTime(2018, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 9000.0,
                            Date = new DateTime(2018, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 6000.0,
                            Date = new DateTime(2018, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 7000.0,
                            Date = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            Amount = 10000.0,
                            Date = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 3000.0,
                            Date = new DateTime(2018, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 4000.0,
                            Date = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 2000.0,
                            Date = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = 12000.0,
                            Date = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Amount = 6000.0,
                            Date = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            Amount = 8000.0,
                            Date = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Amount = 8000.0,
                            Date = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Amount = 9000.0,
                            Date = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            Amount = 4000.0,
                            Date = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            Amount = 11000.0,
                            Date = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 24,
                            Amount = 8000.0,
                            Date = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            Amount = 7000.0,
                            Date = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            Amount = 5000.0,
                            Date = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            Amount = 9000.0,
                            Date = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            Amount = 4000.0,
                            Date = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 29,
                            Amount = 12000.0,
                            Date = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 5,
                            Status = 1
                        },
                        new
                        {
                            Id = 30,
                            Amount = 5000.0,
                            Date = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("VendasWebMvc.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("double");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 1000.0,
                            BirthDate = new DateTime(1998, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "bob@gmail.com",
                            Name = "Bob Brown"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 3500.0,
                            BirthDate = new DateTime(1979, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "maria@gmail.com",
                            Name = "Maria Green"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 2200.0,
                            BirthDate = new DateTime(1988, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "alex@gmail.com",
                            Name = "Alex Grey"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 3000.0,
                            BirthDate = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "martha@gmail.com",
                            Name = "Martha Red"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 4000.0,
                            BirthDate = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "donald@gmail.com",
                            Name = "Donald Blue"
                        },
                        new
                        {
                            Id = 6,
                            BaseSalary = 3000.0,
                            BirthDate = new DateTime(1997, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "bob@gmail.com",
                            Name = "Alex Pink"
                        });
                });

            modelBuilder.Entity("VendasWebMvc.Models.SalesRecord", b =>
                {
                    b.HasOne("VendasWebMvc.Models.Seller", "Seller")
                        .WithMany("Sales")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("VendasWebMvc.Models.Seller", b =>
                {
                    b.HasOne("VendasWebMvc.Models.Department", "Department")
                        .WithMany("Sellers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("VendasWebMvc.Models.Department", b =>
                {
                    b.Navigation("Sellers");
                });

            modelBuilder.Entity("VendasWebMvc.Models.Seller", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
